//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaParcialMondalgo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int PeliculasId { get; set; }
        public string titulo { get; set; }
        public int duracion { get; set; }
        public string clasificacion { get; set; }
        public Nullable<System.DateTime> estreno { get; set; }
        public Nullable<int> GenerosId { get; set; }
    
        public virtual Generos Generos { get; set; }
    }
}
